"""Control-Flow Graph (CFG) validation for generated patches."""

import ast
from dataclasses import dataclass

@dataclass
class CFGWarning:
    """A warning generated by the CFGChecker."""
    message: str
    line_number: int


class CFGChecker(ast.NodeVisitor):
    """Analyzes AST for control-flow issues like unreachable code."""

    def __init__(self) -> None:
        self.warnings: list[CFGWarning] = []

    def check_source(self, source_code: str) -> list[CFGWarning]:
        """Parse source code and check for CFG issues.
        
        Args:
            source_code: Python source code to analyze.
            
        Returns:
            A list of CFGWarning instances.
        """
        self.warnings = []
        try:
            tree = ast.parse(source_code)
            self.visit(tree)
        except SyntaxError:
            # We assume syntax checking happens elsewhere; ignore here
            pass
        return self.warnings

    def _check_block_for_unreachable(self, stmts: list[ast.stmt]) -> None:
        """Check a block of statements for unreachable code."""
        terminal_found = False
        for stmt in stmts:
            if terminal_found:
                self.warnings.append(
                    CFGWarning(
                        message="Unreachable code detected after return/raise/break/continue",
                        line_number=stmt.lineno,
                    )
                )
                break  # Only warn once per block
                
            if isinstance(stmt, (ast.Return, ast.Raise, ast.Break, ast.Continue)):
                terminal_found = True

    def generic_visit(self, node: ast.AST) -> None:
        """Visit generic nodes and check their bodies if they are block-like."""
        for fieldname, value in ast.iter_fields(node):
            if isinstance(value, list) and value and isinstance(value[0], ast.stmt):
                # This is a block of statements (e.g., function body, if body)
                self._check_block_for_unreachable(value)
        super().generic_visit(node)
