"""Property-based tests for validation exception classes (Layer 6 — Validation).

Tests that ``PatchError`` message content always contains the required
diagnostic substrings regardless of the ``patch_preview`` value.

**Validates: Requirements 2.1, 2.2**
"""

from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from local_sage.validation.exceptions import PatchError
from local_sage.validation.patcher import Patcher

# ---------------------------------------------------------------------------
# Constants — the exact message used by Patcher._apply_patch()
# ---------------------------------------------------------------------------

_STANDARD_MESSAGE: str = (
    "No valid diff hunks found in patch — the model likely produced "
    "explanation text instead of a unified diff"
)

# ---------------------------------------------------------------------------
# Property 6: PatchError message always contains both required substrings
# ---------------------------------------------------------------------------


@given(patch_preview=st.text())
@settings(max_examples=200)
def test_patch_error_message_contains_required_substrings(patch_preview: str) -> None:
    """Property 6: PatchError message always contains both required substrings.

    For any arbitrary ``patch_preview`` string, instantiating ``PatchError``
    with the standard message used by ``Patcher._apply_patch()`` always
    produces an exception whose ``message`` attribute contains both
    ``"No valid diff hunks found in patch"`` and ``"explanation text"``.

    **Validates: Requirements 2.1, 2.2**

    Args:
        patch_preview: Arbitrary text generated by Hypothesis to stand in for
            the first 200 characters of a bad patch string.
    """
    exc = PatchError(_STANDARD_MESSAGE, patch_preview=patch_preview)

    assert "No valid diff hunks found in patch" in exc.message, (
        f"Expected 'No valid diff hunks found in patch' in message, got: {exc.message!r}"
    )
    assert "explanation text" in exc.message, (
        f"Expected 'explanation text' in message, got: {exc.message!r}"
    )


@given(patch_preview=st.text())
@settings(max_examples=200)
def test_patch_error_patch_preview_stored_as_given(patch_preview: str) -> None:
    """Property 6 (supplementary): PatchError stores patch_preview unchanged.

    For any arbitrary ``patch_preview`` string, the ``patch_preview``
    attribute on the resulting ``PatchError`` equals the value passed in
    during construction.  This confirms the attribute assignment in
    ``__init__`` is correct regardless of the preview content.

    **Validates: Requirements 2.1, 2.2**

    Args:
        patch_preview: Arbitrary text generated by Hypothesis.
    """
    exc = PatchError(_STANDARD_MESSAGE, patch_preview=patch_preview)

    assert exc.patch_preview == patch_preview, (
        f"patch_preview mismatch — stored {exc.patch_preview!r}, expected {patch_preview!r}"
    )


@given(raw_patch=st.text(min_size=201))
@settings(max_examples=200)
def test_patch_error_preview_truncated_to_200_chars(raw_patch: str) -> None:
    """Property 6 (truncation): patch_preview is at most 200 characters long.

    ``Patcher._apply_patch()`` passes ``patch[:200]`` as the preview.  This
    test verifies that when callers follow that convention the stored preview
    never exceeds 200 characters.

    **Validates: Requirements 2.1, 2.2**

    Args:
        raw_patch: An arbitrary string of at least 201 characters, simulating
            a long non-diff patch as the model might produce.
    """
    preview = raw_patch[:200]
    exc = PatchError(_STANDARD_MESSAGE, patch_preview=preview)

    assert len(exc.patch_preview) <= 200, (
        f"patch_preview length {len(exc.patch_preview)} exceeds 200 chars"
    )


# ---------------------------------------------------------------------------
# Unit tests — direct PatchError construction
# ---------------------------------------------------------------------------


def test_patch_error_direct_construction_contains_required_substrings() -> None:
    """Unit test: directly constructed PatchError message contains both substrings.

    Constructs a ``PatchError`` with the standard message used by
    ``Patcher._apply_patch()`` and asserts that both required diagnostic
    substrings are present without relying on Hypothesis.

    **Validates: Requirements 2.1, 2.2**
    """
    exc = PatchError(_STANDARD_MESSAGE, patch_preview="not a diff")

    assert "No valid diff hunks found in patch" in exc.message
    assert "explanation text" in exc.message


def test_patch_error_stores_patch_preview_attribute() -> None:
    """Unit test: PatchError stores the patch_preview attribute correctly.

    **Validates: Requirements 2.3**
    """
    preview = "this is explanation text, not a diff"
    exc = PatchError(_STANDARD_MESSAGE, patch_preview=preview)

    assert exc.patch_preview == preview


# ---------------------------------------------------------------------------
# Integration tests — PatchError raised by Patcher._apply_patch()
# ---------------------------------------------------------------------------


def test_apply_patch_raises_patch_error_for_non_diff_string() -> None:
    """Integration: _apply_patch() raises PatchError for non-diff explanation text.

    Creates a temporary directory and calls ``Patcher._apply_patch()`` with
    a plain English string that ``whatthepatch.parse_patch()`` will return an
    empty list for.  Asserts that ``PatchError`` is raised and that its
    ``message`` contains both required substrings.

    **Validates: Requirements 2.1, 2.2**
    """
    tmp_dir = Path(tempfile.mkdtemp())
    try:
        patcher = Patcher()
        with pytest.raises(PatchError) as exc_info:
            patcher._apply_patch(tmp_dir, "This is explanation text, not a unified diff.")

        err = exc_info.value
        assert "No valid diff hunks found in patch" in err.message
        assert "explanation text" in err.message
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


def test_apply_patch_raises_patch_error_for_empty_string() -> None:
    """Integration: _apply_patch() raises PatchError for an empty patch string.

    **Validates: Requirements 2.1, 2.2**
    """
    tmp_dir = Path(tempfile.mkdtemp())
    try:
        patcher = Patcher()
        with pytest.raises(PatchError) as exc_info:
            patcher._apply_patch(tmp_dir, "")

        err = exc_info.value
        assert "No valid diff hunks found in patch" in err.message
        assert "explanation text" in err.message
        assert len(err.patch_preview) <= 200
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)


@given(non_diff_text=st.text(min_size=1, max_size=200).filter(
    lambda s: not s.strip().startswith("---")
))
@settings(max_examples=100)
def test_property6_apply_patch_non_diff_raises_patch_error_with_substrings(
    non_diff_text: str,
) -> None:
    """Property 6: any non-diff string passed to _apply_patch raises PatchError
    whose message contains both required substrings.

    Filters out strings that start with ``---`` to avoid accidentally
    generating valid-looking diffs.  Uses a fresh temp directory per
    invocation to isolate filesystem state.

    **Validates: Requirements 2.1, 2.2**

    Args:
        non_diff_text: Arbitrary text that does not start with ``---``.
    """
    tmp_dir = Path(tempfile.mkdtemp())
    try:
        patcher = Patcher()
        try:
            patcher._apply_patch(tmp_dir, non_diff_text)
        except PatchError as err:
            assert "No valid diff hunks found in patch" in err.message, (
                f"Missing required substring in message: {err.message!r}"
            )
            assert "explanation text" in err.message, (
                f"Missing 'explanation text' in message: {err.message!r}"
            )
        except Exception:
            # whatthepatch may raise on some exotic inputs — let it propagate
            # naturally per Requirement 2.1 (no wrapping in PatchError)
            pass
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)
