"""Tests for ``ModelOutputParser.extract_diff()`` — unit and property-based.

Covers extraction from raw diffs, fenced code blocks, prose with embedded diff
sections, and edge cases (empty string, pure prose).

**Validates: Requirements 7.2, 7.6**
"""

from __future__ import annotations

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from local_sage.agent.parser import ModelOutputParser

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture()
def parser() -> ModelOutputParser:
    """Return a fresh ``ModelOutputParser`` instance for each test.

    Returns:
        A new ``ModelOutputParser`` with no shared state.
    """
    return ModelOutputParser()


# ---------------------------------------------------------------------------
# Unit tests
# ---------------------------------------------------------------------------


def test_raw_diff_starting_with_dashes_returned_unchanged(parser: ModelOutputParser) -> None:
    """A raw diff whose first non-whitespace is ``---`` is returned as-is.

    Args:
        parser: Fresh ``ModelOutputParser`` instance.
    """
    raw = (
        "--- a/local_sage/model/client.py\n"
        "+++ b/local_sage/model/client.py\n"
        "@@ -10,1 +10,1 @@\n"
        "-    pass\n"
        "+    return None\n"
    )
    assert parser.extract_diff(raw) == raw


def test_backtick_diff_fence_extracts_content_without_markers(
    parser: ModelOutputParser,
) -> None:
    """Content inside a `` ```diff `` fence is extracted without fence markers.

    Args:
        parser: Fresh ``ModelOutputParser`` instance.
    """
    diff_body = "--- a/foo.py\n+++ b/foo.py\n@@ -1,1 +1,1 @@\n-x=1\n+x=2\n"
    raw = f"Here is the fix:\n```diff\n{diff_body}```\n"
    result = parser.extract_diff(raw)
    assert result is not None
    assert "```" not in result
    assert "---" in result


def test_plain_fence_containing_diff_extracts_content(parser: ModelOutputParser) -> None:
    """A plain `` ``` `` fence whose body contains ``---``/``+++`` is extracted.

    Args:
        parser: Fresh ``ModelOutputParser`` instance.
    """
    diff_body = "--- a/bar.py\n+++ b/bar.py\n@@ -5,1 +5,1 @@\n-old\n+new\n"
    raw = f"Apply this:\n```\n{diff_body}```\n"
    result = parser.extract_diff(raw)
    assert result is not None
    assert "---" in result
    assert "```" not in result


def test_prose_with_embedded_diff_block_extracted_from_first_dash_line(
    parser: ModelOutputParser,
) -> None:
    """Prose with an embedded ``--- a/`` / ``+++ b/`` block is extracted from first ``---``.

    Args:
        parser: Fresh ``ModelOutputParser`` instance.
    """
    raw = (
        "Sure, here is the change you need:\n\n"
        "--- a/local_sage/agent/parser.py\n"
        "+++ b/local_sage/agent/parser.py\n"
        "@@ -1,1 +1,1 @@\n"
        "-old_line\n"
        "+new_line\n"
    )
    result = parser.extract_diff(raw)
    assert result is not None
    assert result.startswith("--- a/local_sage/agent/parser.py")


def test_pure_prose_with_no_diff_content_returns_none(parser: ModelOutputParser) -> None:
    """Pure prose with no diff indicators returns ``None``.

    Args:
        parser: Fresh ``ModelOutputParser`` instance.
    """
    assert parser.extract_diff("This looks like a good fix to me.") is None


def test_empty_string_returns_none(parser: ModelOutputParser) -> None:
    """An empty string returns ``None``.

    Args:
        parser: Fresh ``ModelOutputParser`` instance.
    """
    assert parser.extract_diff("") is None


# ---------------------------------------------------------------------------
# Property 8: extract_diff is idempotent on raw diffs
# ---------------------------------------------------------------------------

# Fixed diff header prefix — any string beginning with this already satisfies
# raw.lstrip().startswith("---"), so no filtering via assume() is needed.
_DIFF_PREFIX = "--- a/foo.py\n+++ b/foo.py\n@@ -1 +1 @@\n-x\n+y\n"


@given(suffix=st.text())
@settings(max_examples=300)
def test_extract_diff_is_idempotent_on_raw_diffs(suffix: str) -> None:
    """Property 8: ``extract_diff`` is idempotent on raw diffs.

    For any string built by prepending a canonical diff header to arbitrary
    text ``suffix``, ``extract_diff`` must return the full string unchanged —
    the method should never modify or truncate a string that already looks
    like a raw diff.

    **Validates: Requirements 7.2, 7.6**

    Args:
        suffix: Arbitrary trailing text generated by Hypothesis.
    """
    raw_diff = _DIFF_PREFIX + suffix
    parser = ModelOutputParser()
    result = parser.extract_diff(raw_diff)
    assert result == raw_diff, (
        f"extract_diff modified a raw-diff string.\n"
        f"Input  : {raw_diff!r}\n"
        f"Output : {result!r}"
    )


# ---------------------------------------------------------------------------
# Property 3 (partial): result always contains "---" when not None
# ---------------------------------------------------------------------------


@given(s=st.text())
@settings(max_examples=300)
def test_extract_diff_result_always_contains_dashes_when_not_none(s: str) -> None:
    """Property 3 (partial): any non-``None`` result from ``extract_diff`` contains ``"---"``.

    For any arbitrary input string, when ``extract_diff`` returns a value
    (not ``None``), that value must contain the ``"---"`` substring, which
    is the minimum marker for a unified diff header line.

    **Validates: Requirements 7.2, 7.6**

    Args:
        s: Arbitrary text generated by Hypothesis.
    """
    parser = ModelOutputParser()
    result = parser.extract_diff(s)
    if result is not None:
        assert "---" in result, (
            f"extract_diff returned a non-None value without '---'.\n"
            f"Input  : {s!r}\n"
            f"Output : {result!r}"
        )


# ---------------------------------------------------------------------------
# Forgiving parser fallback tests
# (based on exact raw outputs from qwen2.5-coder:7b observed in live harness)
# ---------------------------------------------------------------------------


class TestFallbackExtractSearchReplaceBlocks:
    """Forgiving fallback tests for extract_search_replace_blocks.

    Each test uses a raw string that mirrors the exact (or near-exact)
    output observed during live harness runs.  The strict form is always
    tested first as a control.
    """

    def test_strict_form_still_works(self, parser: ModelOutputParser) -> None:
        """Strict <<<<<<< SEARCH / >>>>>>> REPLACE is always the first choice."""
        raw = (
            "<<<<<<< SEARCH\n"
            "def func1(): return 'A'\n"
            "=======\n"
            "def func1(): return 'C'\n"
            ">>>>>>> REPLACE\n"
        )
        blocks = parser.extract_search_replace_blocks(raw)
        assert len(blocks) == 1
        assert blocks[0].search == "def func1(): return 'A'"
        assert blocks[0].replace == "def func1(): return 'C'"

    def test_angle_bracket_fallback_no_labels(self, parser: ModelOutputParser) -> None:
        """Angled brackets without SEARCH/REPLACE text labels are accepted."""
        raw = (
            "<<<<<<\n"
            "def func1(): return 'A'\n"
            "=======\n"
            "def func1(): return 'C'\n"
            ">>>>>>>\n"
        )
        blocks = parser.extract_search_replace_blocks(raw)
        assert len(blocks) == 1
        assert "func1" in blocks[0].search
        assert "'C'" in blocks[0].replace

    def test_keyword_colon_form_fenced(self, parser: ModelOutputParser) -> None:
        """SEARCH: / REPLACE: colon form inside ```plaintext fences is parsed.

        This is the primary format-drift pattern from qwen2.5-coder:7b.
        """
        raw = (
            "1. Loop control variable not used:\n"
            "   ```plaintext\n"
            "   SEARCH: def func1(): return 'A'\n"
            "   REPLACE: def func1(): return 'C'\n"
            "   ```\n"
        )
        blocks = parser.extract_search_replace_blocks(raw)
        assert len(blocks) == 1
        assert "'A'" in blocks[0].search
        assert "'C'" in blocks[0].replace

    def test_keyword_colon_multiple_pairs(self, parser: ModelOutputParser) -> None:
        """Multiple SEARCH: / REPLACE: pairs are all extracted."""
        raw = (
            "SEARCH: old_func1\n"
            "REPLACE: new_func1\n"
            "SEARCH: old_func2\n"
            "REPLACE: new_func2\n"
        )
        blocks = parser.extract_search_replace_blocks(raw)
        assert len(blocks) == 2
        assert "old_func1" in blocks[0].search
        assert "old_func2" in blocks[1].search

    def test_bare_keyword_section_form(self, parser: ModelOutputParser) -> None:
        """Bare SEARCH / REPLACE section headings (no colons, no brackets) are parsed."""
        raw = (
            "SEARCH\n"
            "def func1(): return 'A'\n"
            "REPLACE\n"
            "def func1(): return 'C'\n"
        )
        blocks = parser.extract_search_replace_blocks(raw)
        assert len(blocks) == 1
        assert "'A'" in blocks[0].search
        assert "'C'" in blocks[0].replace

    def test_strict_preferred_when_both_forms_present(
        self, parser: ModelOutputParser
    ) -> None:
        """Strict blocks are returned even when loose form also appears."""
        raw = (
            "<<<<<<< SEARCH\n"
            "strict_search\n"
            "=======\n"
            "strict_replace\n"
            ">>>>>>> REPLACE\n"
            "\n"
            "SEARCH: loose_search\n"
            "REPLACE: loose_replace\n"
        )
        blocks = parser.extract_search_replace_blocks(raw)
        # Must return only the strict block — loose fallback should not fire
        assert len(blocks) == 1
        assert blocks[0].search == "strict_search"

    def test_empty_string_returns_empty_list(self, parser: ModelOutputParser) -> None:
        """Empty input yields an empty list from both phases."""
        assert parser.extract_search_replace_blocks("") == []

    def test_pure_prose_returns_empty_list(self, parser: ModelOutputParser) -> None:
        """Plain prose with no recognisable pattern yields an empty list."""
        assert (
            parser.extract_search_replace_blocks(
                "Sure! I'd be happy to help with that change."
            )
            == []
        )

